[package]
name = "by-axum"
version = "0.1.4"
edition = "2021"
description = "Library satisfying Biyard API convention"
license = "MIT"
keywords = ["axum", "lambda", "api", "serverless"]
repository = "https://github.com/biyard/biyard-api.git"

[dependencies]
aide = { version = "0.13.4", features = ["axum"] }
axum = "0.7.9"
axum-core = "0.4.5"
dioxus-aws = { version = "0.6.4", optional = true }
http = { version = "1.1.0", optional = true }
lambda_http = { version = "0.13.0", optional = true }
lambda_runtime = { version = "0.13.0", optional = true }
slog = "2.7.0"
slog-term = "2.9.1"
static_str_ops = "0.1.2"
tokio = { version = "1.41.1", features = ["net"] }
tower = { version = "0.5.1", optional = true }
tower-http = { version = "0.6.2", features = ["cors", "compression-gzip", "compression-deflate", "trace"], optional = true }
tower-service = "0.3.3"

[features]
lambda = ["dioxus-aws", "lambda_runtime", "lambda_http", "tower", "http", "tower-http"]
