name: PR Checking

on:
  pull_request:
      types: [opened, synchronize, reopened]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-deployment:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          ssh-key: ${{ secrets.PULL_KEY_REPO }}

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
          target: wasm32-unknown-unknown
          toolchain: stable

      - name: test
        run: cargo test

      - name: test with server feature
        run: cargo test --features server

      - name: Building packages
        run: |
          make build
